// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB5CpG_mEhnje5woBt06FzVkqr9sMfG_vk',
    appId: '1:701213161860:web:c575b09b7ea03f4ac105d1',
    messagingSenderId: '701213161860',
    projectId: 'caffeine-78360',
    authDomain: 'caffeine-78360.firebaseapp.com',
    storageBucket: 'caffeine-78360.appspot.com',
    measurementId: 'G-9CSLC4XBGJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDHW38EQyY1GOogenbeVL1lhqyd0PQYI2U',
    appId: '1:701213161860:android:2e1e2e699e7e2c4dc105d1',
    messagingSenderId: '701213161860',
    projectId: 'caffeine-78360',
    storageBucket: 'caffeine-78360.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAeECm4_Jf5pgG4V6aWYTEINOezIfS6f8I',
    appId: '1:701213161860:ios:3fd9bfa3d9cdd123c105d1',
    messagingSenderId: '701213161860',
    projectId: 'caffeine-78360',
    storageBucket: 'caffeine-78360.appspot.com',
    iosBundleId: 'com.example.musicApp',
  );
}
